import Quickshell
import "./modules/bar"
import "./modules/launcher"
import "./modules/notifications"
import "./modules/power"
import "./modules/osd"
import "./modules/network"
import "./modules/bluetooth"
import "./modules/battery"
import "./modules/calendar"
import "./modules/clipboard"
import "./modules/media"
import "./modules/overview"
import "./modules/settings"

Scope {
    Bar {}
    Launcher {}
    NotificationPopups {}
    NotificationCenter {}
    PowerMenu {}
    Osd {}
    NetworkPopup {}
    BluetoothPopup {}
    BatteryPopup {}
    CalendarPopup {}
    ClipboardPopup {}
    MediaPopup {}
    Overview {}
    SettingsWindow {}
}
