import Quickshell
import "./modules/bar"
import "./modules/launcher"
import "./modules/notifications"
import "./modules/polkit"
import "./modules/power"
import "./modules/osd"
import "./modules/network"
import "./modules/bluetooth"
import "./modules/audio"
import "./modules/battery"
import "./modules/dashboard"
import "./modules/capture"
import "./modules/calendar"
import "./modules/clipboard"
import "./modules/media"
import "./modules/overview"
import "./modules/quicksettings"
import "./modules/settings"
import "./modules/dock"

Scope {
    Bar {}
    Launcher {}
    NotificationPopups {}
    NotificationCenter {}
    PowerMenu {}
    PolkitDialog {}
    CapturePopup {}
    Osd {}
    NetworkPopup {}
    BluetoothPopup {}
    BatteryPopup {}
    AudioPopup {}
    CalendarPopup {}
    ClipboardPopup {}
    MediaPopup {}
    Overview {}
    Dashboard {}
    QuickSettings {}
    SettingsWindow {}
    Dock {}
}
