-- See https://wiki.hypr.land/Configuring/Start/

require("monitors")
require("autostart")
require("keybinds")

-- Generated by matugen (see ~/dotfiless/matugen); falls back to a fixed
-- palette before the first wallpaper is ever picked (SUPER + W).
package.loaded["colors"] = nil
local ok, colors = pcall(require, "colors")
if not ok then
    colors = { primary = "38bdf8", outline = "8087a2" }
end

-- Makes Qt apps render with the GTK3 theme (and thus matugen's colors,
-- via the generated ~/.config/gtk-3.0/gtk.css) instead of plain Qt defaults.
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

hl.config({
    general = {
        layout = "dwindle",

        gaps_in     = 6,
        gaps_out    = 6,
        border_size = 2,

        col = {
            active_border = "rgba(" .. colors.primary .. "ff)",
            inactive_border = "rgba(" .. colors.outline .. "ff)",
        },
    },

    decoration = {
        rounding         = 10,
        active_opacity   = 1.0,
        inactive_opacity = 0.85,

        blur = {
            enabled = true,
            size    = 8,
            passes  = 2,
        },
    },

    animations = {
        enabled = true,
    },

    -- Focusing a window by address (what the dock and the overview do when you
    -- click an entry) otherwise teleports the pointer into the middle of that
    -- window, which is jarring when you clicked a dock icon at the bottom of
    -- the screen. Set this back to false to get Hyprland's warping behaviour.
    cursor = {
        no_warps = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-- eDP-1 runs at scale 1.25, and XWayland clients cannot scale themselves --
-- without this they are rendered at 1x and upscaled, which looks soft. Telling
-- XWayland to use scale 1 and letting the compositor handle it keeps them
-- sharp. Costs nothing when no XWayland client is running.
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.curve("mangoOpen",    { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("mangoClose",   { type = "bezier", points = { {0.4, 0},  {1, 1} } })
hl.curve("mangoFocus",   { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("mangoFadeOut", { type = "bezier", points = { {0.4, 0},  {1, 1} } })

hl.animation({ leaf = "windows",    enabled = true, speed = 2.6, bezier = "mangoOpen",  style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.0, bezier = "mangoClose", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 1.4, bezier = "mangoFocus" })
hl.animation({ leaf = "fade",       enabled = true, speed = 2.6, bezier = "mangoOpen" })
hl.animation({ leaf = "fadeOut",    enabled = true, speed = 2.0, bezier = "mangoFadeOut" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.3, bezier = "mangoOpen",  style = "slide" })
hl.animation({ leaf = "layers",     enabled = true, speed = 2.6, bezier = "mangoOpen",  style = "popin 80%" })

-- Quickshell bar + notification toasts: slide in from their anchored edge
-- instead of the default "popin", which pops from the centre of the screen
-- and looks wrong for an edge-anchored panel.
hl.layer_rule({ name = "quickshell-slide", match = { namespace = "^quickshell$" }, animation = "slide" })

-- Popup cards (launcher, quick settings, calendar, media...) already animate
-- themselves in QML, and a directional slide clips round content against the
-- screen edge mid-transition, so the surface just fades.
hl.layer_rule({ name = "quickshell-popup-fade", match = { namespace = "^quickshell-popup$" }, animation = "fade" })

-- The dock's own surface stays mapped so it can keep receiving hover; it
-- animates itself in QML, so the compositor must not also animate it.
hl.layer_rule({ name = "quickshell-dock", match = { namespace = "^quickshell-dock$" }, animation = "none" })

-- The shell's surfaces are translucent (see PopupCard and BarConfig.barOpacity),
-- which only reads as glass if the compositor blurs what is behind them. Blur
-- is already on globally for windows; these opt the shell's own layers in.
--
-- ignore_alpha is not optional here: every one of these layers is a screen-sized
-- transparent surface with a small card drawn somewhere inside it, so without a
-- threshold the compositor blurs the entire desktop the moment a popup opens.
hl.layer_rule({ name = "quickshell-blur",       match = { namespace = "^quickshell$" },       blur = true, ignore_alpha = 0.1 })
hl.layer_rule({ name = "quickshell-popup-blur", match = { namespace = "^quickshell-popup$" }, blur = true, ignore_alpha = 0.1 })
hl.layer_rule({ name = "quickshell-dock-blur",  match = { namespace = "^quickshell-dock$" },  blur = true, ignore_alpha = 0.1 })

-- Window rules. There were none, so everything tiled -- including the things
-- that are not really windows.

-- Firefox's picture-in-picture is a small always-on-top video, and tiling it
-- gives it half the screen.
hl.window_rule({
    name  = "float-picture-in-picture",
    match = { title = "^Picture-in-Picture$" },
    float = true,
})

-- Portal file choosers (the Open/Save dialog most apps now use) are dialogs,
-- not documents.
hl.window_rule({
    name  = "float-portal-dialogs",
    match = { class = "^xdg-desktop-portal-gtk$" },
    float = true,
})
