-- See https://wiki.hypr.land/Configuring/Start/

require("monitors")
require("autostart")
require("keybinds")

-- Generated by matugen (see ~/dotfiless/matugen); falls back to a fixed
-- palette before the first wallpaper is ever picked (SUPER + W).
package.loaded["colors"] = nil
local ok, colors = pcall(require, "colors")
if not ok then
    colors = { primary = "38bdf8", outline = "8087a2" }
end

-- Makes Qt apps render with the GTK3 theme (and thus matugen's colors,
-- via the generated ~/.config/gtk-3.0/gtk.css) instead of plain Qt defaults.
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

hl.config({
    general = {
        layout = "dwindle",

        gaps_in     = 6,
        gaps_out    = 6,
        border_size = 2,

        col = {
            active_border = "rgba(" .. colors.primary .. "ff)",
            inactive_border = "rgba(" .. colors.outline .. "ff)",
        },
    },

    decoration = {
        rounding         = 10,
        active_opacity   = 1.0,
        inactive_opacity = 0.85,

        blur = {
            enabled = true,
            size    = 8,
            passes  = 2,
        },
    },

    animations = {
        enabled = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.curve("mangoOpen",    { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("mangoClose",   { type = "bezier", points = { {0.4, 0},  {1, 1} } })
hl.curve("mangoFocus",   { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("mangoFadeOut", { type = "bezier", points = { {0.4, 0},  {1, 1} } })

hl.animation({ leaf = "windows",    enabled = true, speed = 2.6, bezier = "mangoOpen",  style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.0, bezier = "mangoClose", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 1.4, bezier = "mangoFocus" })
hl.animation({ leaf = "fade",       enabled = true, speed = 2.6, bezier = "mangoOpen" })
hl.animation({ leaf = "fadeOut",    enabled = true, speed = 2.0, bezier = "mangoFadeOut" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.3, bezier = "mangoOpen",  style = "slide" })
hl.animation({ leaf = "layers",     enabled = true, speed = 2.6, bezier = "mangoOpen",  style = "popin 80%" })

-- Quickshell bar + notification toasts: slide in from their anchored edge
-- instead of the default "popin", which pops from the centre of the screen
-- and looks wrong for an edge-anchored panel.
hl.layer_rule({ name = "quickshell-slide", match = { namespace = "^quickshell$" }, animation = "slide" })

-- Popup cards (launcher, quick settings, calendar, media...) already animate
-- themselves in QML, and a directional slide clips round content against the
-- screen edge mid-transition, so the surface just fades.
hl.layer_rule({ name = "quickshell-popup-fade", match = { namespace = "^quickshell-popup$" }, animation = "fade" })
